[[headers]]
  for = "/*.woff2"
  [headers.values]
    # Cache fonts for one year
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.(svg|webp|png|avif|png|jpeg)"
  [headers.values]
    # Store cache-busted images for one year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    # Cache for one week, but can be reused for one day
    Cache-Control = "public, max-age=604800, stale-while-revalidate=86400"
