[build]
command = "pnpm run build"
publish = "dist"

[[headers]]
  for = "/*.cast"
  [headers.values]
    # Asciinema mime-type
    Content-Type = "application/x-asciicast"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    # Cache fonts for one year
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.(svg|webp|png|avif|png|jpeg|mp3|wasm|cast)"
  [headers.values]
    # Store cache-busted assets for one year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    # Store cache-busted CSS for one year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/tooltips/meta.json"
  [headers.values]
    # Cache for one week, but can be reused for one day
    Cache-Control = "public, max-age=604800, stale-while-revalidate=86400"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self'; form-action 'self'; font-src 'self'; connect-src 'self'; frame-src 'self'; frame-ancestors 'none'; object-src 'none'"

[[headers]]
  for = "/tooltips/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self'; form-action 'self'; font-src 'self'; connect-src 'self'; frame-src 'self'; frame-ancestors 'none'; object-src 'none'"

[[headers]]
  for = "/blog/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; script-src 'self' 'unsafe-inline' https://esm.sh 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' https://*.githubusercontent.com data:; form-action 'self'; font-src 'self'; connect-src 'self' data: https://api.webstatus.dev; frame-src 'self'; frame-ancestors 'none'; object-src 'none'"

[[redirects]]
  from = "/"
  to = "/hello/"
  status = 301
  force = true

[[redirects]]
  from = "/mind-map"
  to = "/tooltips/"
  status = 301
  force = false

[[redirects]]
  from = "/daily-drivers/"
  to = "/uses"
  status = 301
  force = false

[[redirects]]
  from = "/tooltips/* slug=:slug"
  to = "/tooltips/:splat/"
  status = 301
  force = false
