[[headers]]
  for = "/*.woff2"
  [headers.values]
    # Cache fonts for one year
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.(svg|webp|png|avif|png|jpeg)"
  [headers.values]
    # Store cache-busted images for one year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    # Cache for one week, but can be reused for one day
    Cache-Control = "public, max-age=604800, stale-while-revalidate=86400"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self'; form-action 'self'; font-src 'self'; connect-src 'self'; frame-src 'self'; frame-ancestors 'none'; object-src 'none'"

[[headers]]
  for = "/blog/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; script-src 'self' 'unsafe-inline' https://esm.sh 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' https://*.githubusercontent.com; form-action 'self'; font-src 'self'; connect-src 'self' data:; frame-src 'self'; frame-ancestors 'none'; object-src 'none'"
