name: Portfolio
run-name: Running actions by @${{ github.actor }}

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  e2e:
    name: "Deploy"
    runs-on: ubuntu-latest
    environment: production
    container:
      image: mcr.microsoft.com/playwright:v1.41.0-jammy
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get -y install jq
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Mark Github workspace as safe
        run: |
          git config --global --add safe.directory $PWD
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install deploy cli
        run: pnpm install netlify-cli
      - name: Install dependencies
        run: pnpm i
      - name: Build
        run: pnpm netlify build --offline
      - name: Deploy
        id: deploy
        run: |
          NETLIFY_PREVIEW_URL=$(pnpm netlify deploy \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --json \
          | jq -r ".deploy_url")
          echo Preview is deployed @ $NETLIFY_PREVIEW_URL
          echo "NETLIFY_PREVIEW_URL=$NETLIFY_PREVIEW_URL" >> "$GITHUB_OUTPUT"
      - name: Run Playwright tests
        run: pnpm e2e
        env:
          PLAYWRIGHT_BASE_URL: ${{ steps.deploy.outputs.NETLIFY_PREVIEW_URL }}
